version: '3'

tasks:
  run-service:
    cmds:
      - docker compose up -d
    silent: true
  delete-service:
    cmds:
      - docker compose down --rmi local
      - docker volume rm postgres_storage_volume
    silent: true
  generate-grpc:
    cmds:
      - protoc --go_out=api/grpc --go_opt=paths=source_relative --go-grpc_out=api/grpc --go-grpc_opt=paths=source_relative -I api/grpc api/grpc/auth_service.proto
    silent: true
