DROP SCHEMA IF EXISTS auth CASCADE;

CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users
(
  userId UUID PRIMARY KEY,
  login VARCHAR(60) NOT NULL,
  password VARCHAR(60) NOT NULL,
  CONSTRAINT uniqueLogin UNIQUE(login)
  CONSTRAINT validLogin CHECK(LENGTH(login) > 0),
  CONSTRAINT validPassword CHECK(LENGTH(password) > 0)
);