services:
  user-storage:
    container_name: user_storage
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512m
        reservations:
          cpus: "0.25"
          memory: 256m
    volumes:
      - type: bind
        source: ./initdb/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
        read_only: false
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 10s
    restart: always
    tty: true
    stdin_open: true
    networks:
      - auth-network

volumes:
  pg-data:
    name: postgres_storage_volume
